#!/bin/bash
export JAVA_HOME=/home/linuxmint/GitHub/jdk1.8.0_172
export ANDROID_HOME=/home/linuxmint/GitHub/Android
export ANDROID_SDK_ROOT=/home/linuxmint/GitHub/Android

if [[ ${1} != "install" ]]; then
    echo 'Building:'
    npm run build-dev-cordova-android | tee /tmp/cordova-build-output.log
fi

#if [[ $? == 0 ]]; then
#    echo 'Installing..'
#    ${ANDROID_HOME}/platform-tools/adb install $(cat /tmp/cordova-build-output.log | tail -n1)
#fi
